[package]
name = "rtmp_server"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
bytes = "1"
tracing = "0.1.40"
tracing-subscriber = "0.3.20"
thiserror = "1.0.40"
rand = "0.9.2"
flv = { path = "flv" }

[lints]
workspace = true
