[package]
name = "rtmp"
version = "0.1.0"
edition = "2024"

[dependencies]
bytes = "1"
tracing = "0.1.40"
thiserror = "1.0.40"
url = "2.5.2"
rand = "0.9.2"

[dev-dependencies]
tracing-subscriber = "0.3.20"

[lints]
workspace = true
