name: Rust - release build
on:
    workflow_dispatch: {}

jobs:
    binaries-linux-x86_64:
        runs-on: ubuntu-24.04
        steps:
            - name: 游 Install system dependencies
              run: |
                  sudo apt-get update -y -qq
                  sudo apt-get install -y libegl1-mesa-dev libgl1-mesa-dri libxcb-xfixes0-dev ffmpeg libavcodec-dev libavformat-dev libavfilter-dev libavdevice-dev libopus-dev

            - name: Show `FFmpeg` version
              run: ffmpeg -version

            - name: 游댢 Install the rust toolchain
              uses: dtolnay/rust-toolchain@stable

            - name: 游닌 Checkout repo
              uses: actions/checkout@v4

            - name: 游닍 Package
              run: cargo run -p tools --bin package_for_release
            
            - name: Run dependency check
              run: ./tools/build/smelter/dependency_check

            - uses: actions/upload-artifact@v4
              with:
                name: smelter_linux_x86_64.tar.gz
                path: tools/build/smelter_linux_x86_64.tar.gz

            - uses: actions/upload-artifact@v4
              with:
                name: smelter_with_web_renderer_linux_x86_64.tar.gz
                path: tools/build/smelter_with_web_renderer_linux_x86_64.tar.gz

    binaries-linux-aarch64:
        runs-on: ubuntu-24.04-arm
        steps:
            - name: 游 Install system dependencies
              run: |
                  sudo apt-get update -y -qq
                  sudo apt-get install -y libegl1-mesa-dev libgl1-mesa-dri libxcb-xfixes0-dev ffmpeg libavcodec-dev libavformat-dev libavfilter-dev libavdevice-dev libopus-dev curl git build-essential libssl-dev pkg-config libclang-dev

            - name: Show `FFmpeg` version
              run: ffmpeg -version

            - name: 游댢 Install the rust toolchain
              uses: dtolnay/rust-toolchain@stable

            - name: 游닌 Checkout repo
              uses: actions/checkout@v4

            - name: 游닍 Package
              run: cargo run -p tools --bin package_for_release

            - name: Run dependency check
              run: ./tools/build/smelter/dependency_check

            - uses: actions/upload-artifact@v4
              with:
                name: smelter_linux_aarch64.tar.gz
                path: tools/build/smelter_linux_aarch64.tar.gz

    binaries-macos-x86_64:
        runs-on: macos-15-intel
        steps:
            - name: 游 Install system dependencies
              run: brew install ffmpeg

            - name: Show `FFmpeg` version
              run: ffmpeg -version

            - name: 游댢 Install the rust toolchain
              uses: dtolnay/rust-toolchain@stable

            - name: 游닌 Checkout repo
              uses: actions/checkout@v4

            - name: 游닍 Package
              run: cargo run -p tools --bin package_for_release

            - uses: actions/upload-artifact@v4
              with:
                name: smelter_darwin_x86_64.tar.gz
                path: tools/build/smelter_darwin_x86_64.tar.gz

            - uses: actions/upload-artifact@v4
              with:
                name: smelter_with_web_renderer_darwin_x86_64.tar.gz
                path: tools/build/smelter_with_web_renderer_darwin_x86_64.tar.gz

    binaries-macos-aarch64:
        runs-on: macos-15
        steps:
            - name: 游 Install system dependencies
              run: brew install ffmpeg

            - name: Show `FFmpeg` version
              run: ffmpeg -version

            - name: 游댢 Install the rust toolchain
              uses: dtolnay/rust-toolchain@stable

            - name: 游닌 Checkout repo
              uses: actions/checkout@v4

            - name: 游닍 Package
              run: cargo run -p tools --bin package_for_release

            - name: Run dependency check
              run: ./tools/build/smelter/dependency_check

            - uses: actions/upload-artifact@v4
              with:
                name: smelter_darwin_aarch64.tar.gz
                path: tools/build/smelter_darwin_aarch64.tar.gz

            - uses: actions/upload-artifact@v4
              with:
                name: smelter_with_web_renderer_darwin_aarch64.tar.gz
                path: tools/build/smelter_with_web_renderer_darwin_aarch64.tar.gz
