name: Rust - lint
on:
    workflow_dispatch: {}
    push:
        branches: [master]
    pull_request:
        types: [opened, synchronize]

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
    lint:
        runs-on: ubuntu-24.04
        steps:
            - name: ğŸ›  Install system dependencies
              run: |
                  sudo apt-get update -y -qq
                  sudo apt-get install -y mesa-vulkan-drivers libegl1-mesa-dev libgl1-mesa-dri libxcb-xfixes0-dev ffmpeg libavcodec-dev libavformat-dev libavfilter-dev libavdevice-dev libopus-dev

            - name: ğŸ”§ Install the rust toolchain
              uses: dtolnay/rust-toolchain@stable
              with:
                  components: rustfmt, clippy

            - name: Install pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: 9

            - name: ğŸ“¥ Checkout repo
              uses: actions/checkout@v4

            - name: ğŸ“ Rust cache
              uses: Swatinem/rust-cache@v2

            - name: ğŸª¢ Generate Chromium Embedded Framework bindings
              run: cargo build --package compositor_chromium

            - name: ğŸ“– Check formatting
              run: cargo fmt --all --check

            - name: ğŸ“ Run clippy
              run: cargo clippy --workspace --all-targets --all-features -- -D clippy::todo -D warnings

            - name: ğŸ“„ Generate JSON schema
              working-directory: ./generate
              run: |
                cargo run --bin generate_from_types -- --check
